### ISSUE TITLE
Powershell doesn't interpret '-' arguments correctly : Unexpected token '-s'

### ISSUE THREAD

**Issue by WebF0x** [bitwes/gut-extension#33]
Gut-extension: 2.2.0
Godot-tools: 2.0.0
Windows 10

Note: Careful when you'll test, I think there's something wrong with godot-tools' release. It says the version is 2.0.0 but I get this error, as if you last PR adding getGodotPath is not included:

```
2024-02-28 20:38:10.171 [error] Error: command 'godotTools.getGodotPath' not found
    at k.n (vscode-file://vscode-app/c:/Users/Bob/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1587:12345)
    at k.executeCommand (vscode-file://vscode-app/c:/Users/Bob/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1587:12274)
```

Anyhow, I installed it from their master branch: https://nightly.link/godotengine/godot-vscode-plugin/workflows/ci/master/godot-tools.zip

Now I get this error:

```
PS C:\Users\Bob\Desktop\GodotProjects\TestProjectVscode> "c:/Program Files (x86)/Steam/steamapps/common/Godot Engine/godot.windows.opt.tools.64.exe" -s res://addons/gut/gut_cmdln.gd  -d 
At line:1 char:93
+ ... amapps/common/Godot Engine/godot.windows.opt.tools.64.exe" -s res://a ...      
+                                                                ~~
Unexpected token '-s' in expression or statement.
At line:1 char:96
+ ... /godot.windows.opt.tools.64.exe" -s res://addons/gut/gut_cmdln.gd  -d
+                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Unexpected token 'res://addons/gut/gut_cmdln.gd' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken
```

I don't know by what [cursed Powershell dark magic](https://stackoverflow.com/a/41439826), but if I add an `&` at the start it runs Gut correctly:

```
PS C:\Users\Bob\Desktop\GodotProjects\TestProjectVscode> & "c:/Program Files (x86)/Steam/steamapps/common/Godot Engine/godot.windows.opt.tools.64.exe" -s res://addons/gut/gut_cmdln.gd  -d 
PS C:\Users\Bob\Desktop\GodotProjects\TestProjectVscode> Godot Engine v4.2.1.stable.official.b09f793f5 - https://godotengine.org
Vulkan API 1.3.260 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 2070
 
 ---  Gut  ---
[INFO]:  using [C:/Users/Bob/AppData/Roaming/Godot/app_userdata/TestProjectVscode] for temporary output.
Godot version:  4.2.1
GUT version:  9.1.1
```

![image](https://github.com/bitwes/gut-extension/assets/5454643/f64ddc20-694a-4702-a7e0-343ee319d0cf)

**Comment by bitwes** [comment]
The extension usually adds in the & for you.  For some reason it's not detecting that the shell is powershell and not putting in the &.  I got a release that should be coming out in a day or so that changes shell detection and offers up more settings to make working around stuff like this easier.  

I'll comment when I have it all merged.
